# Generated by Django 5.2.4 on 2025-07-22 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_lanzamiento', models.DateField(verbose_name='Fecha de Lanzamiento')),
                ('director', models.CharField(max_length=100, verbose_name='Director')),
                ('actores', models.TextField(help_text='Separar actores por comas', verbose_name='Actores Principales')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='peliculas/portadas/', verbose_name='Portada de la Película')),
                ('trailer_url', models.URLField(blank=True, null=True, verbose_name='URL del Trailer (YouTube/Vimeo)')),
                ('puntuacion_media', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Puntuación Media')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-fecha_lanzamiento', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_escritos', to=settings.AUTH_USER_MODEL, verbose_name='Autor del Comentario')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.pelicula', verbose_name='Película')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Puntuación (1-5)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Calificación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='blog.pelicula', verbose_name='Película')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('pelicula', 'usuario')},
            },
        ),
    ]
