# Generated by Django 5.2.4 on 2025-08-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='aprobado',
            field=models.BooleanField(default=True, verbose_name='Aprobado'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='categorias',
            field=models.ManyToManyField(related_name='peliculas', to='blog.categoria'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='Descripcion',
            field=models.TextField(default='Sin sinopsis', verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
