# Generated by Django 5.2.4 on 2025-08-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categoria_remove_pelicula_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='Descripcion',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(blank=True, help_text='Breve descripción de la película', null=True, verbose_name='Sinopsis'),
        ),
    ]
