# Generated by Django 5.2.4 on 2025-08-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_pelicula_descripcion_pelicula_sinopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(max_length=500, verbose_name='Comentario'),
        ),
    ]
