# Generated by Django 5.2.4 on 2025-08-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comentario_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='plataforma_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace a Plataforma'),
        ),
    ]
